import { MenuItem, MenuCategory, MenuOptionGroup, MenuOption } from '../types/menuItem';

// 菜單分類模擬數據
export const mockMenuCategories: MenuCategory[] = [
  {
    id: 'cat001',
    name: '主餐',
    description: '各種不同風味的雞排主餐',
    displayOrder: 1,
    type: 'main_dish',
    imageUrl: 'https://example.com/images/main-dishes.jpg',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'cat002',
    name: '配餐',
    description: '各種可搭配主餐的小吃',
    displayOrder: 2,
    type: 'side_dish',
    imageUrl: 'https://example.com/images/side-dishes.jpg',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'cat003',
    name: '飲料',
    description: '各種冷熱飲品',
    displayOrder: 3,
    type: 'drink',
    imageUrl: 'https://example.com/images/drinks.jpg',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'cat004',
    name: '甜點',
    description: '各種特色甜點',
    displayOrder: 4,
    type: 'dessert',
    imageUrl: 'https://example.com/images/desserts.jpg',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'cat005',
    name: '套餐',
    description: '各種優惠組合套餐',
    displayOrder: 5,
    type: 'combo',
    imageUrl: 'https://example.com/images/combos.jpg',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'cat006',
    name: '季節限定',
    description: '季節性限定產品',
    displayOrder: 6,
    type: 'seasonal',
    imageUrl: 'https://example.com/images/seasonal.jpg',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z'
  }
];

// 菜單選項模擬數據
const spicyLevelOptions: MenuOption[] = [
  { id: 'opt001', name: '不辣', description: '完全不辣', price: 0, isDefault: true },
  { id: 'opt002', name: '小辣', description: '微微的辣度', price: 0 },
  { id: 'opt003', name: '中辣', description: '適中的辣度', price: 0 },
  { id: 'opt004', name: '大辣', description: '重口味的辣度', price: 5 }
];

const sizeOptions: MenuOption[] = [
  { id: 'opt005', name: '標準份', description: '標準大小', price: 0, isDefault: true },
  { id: 'opt006', name: '大份', description: '1.5倍份量', price: 30 },
  { id: 'opt007', name: '超值份', description: '2倍份量', price: 55 }
];

const toppingsOptions: MenuOption[] = [
  { id: 'opt008', name: '起司', description: '增加起司', price: 15 },
  { id: 'opt009', name: '培根', description: '增加培根', price: 20 },
  { id: 'opt010', name: '炸蛋', description: '增加炸蛋', price: 15 },
  { id: 'opt011', name: '泡菜', description: '增加泡菜', price: 10 },
  { id: 'opt012', name: '洋蔥', description: '增加洋蔥', price: 5 }
];

// 菜單選項組模擬數據
const mockOptionGroups: MenuOptionGroup[] = [
  {
    id: 'group001',
    name: '辣度選擇',
    description: '選擇您喜好的辣度',
    required: true,
    multiSelect: false,
    minSelect: 1,
    maxSelect: 1,
    options: spicyLevelOptions
  },
  {
    id: 'group002',
    name: '份量選擇',
    description: '選擇您喜好的份量',
    required: true,
    multiSelect: false,
    minSelect: 1,
    maxSelect: 1,
    options: sizeOptions
  },
  {
    id: 'group003',
    name: '加料選擇',
    description: '選擇您喜好的加料',
    required: false,
    multiSelect: true,
    minSelect: 0,
    maxSelect: 5,
    options: toppingsOptions
  }
];

// 菜單項目模擬數據
export const mockMenuItems: MenuItem[] = [
  {
    id: 'item001',
    name: '台式香酥雞排',
    description: '使用傳統台式配方醃製，酥脆外表、多汁內裡',
    categoryId: 'cat001',
    categoryName: '主餐',
    price: 90,
    imageUrl: 'https://example.com/images/fried-chicken-main.jpg',
    thumbnailUrl: 'https://example.com/images/fried-chicken-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 100,
    unit: '份',
    preparationTime: 5,
    isRecommended: true,
    isSpecial: false,
    isActive: true,
    nutritionInfo: {
      calories: 350,
      protein: 25,
      carbs: 30,
      fat: 15,
      allergens: ['穀物', '大豆']
    },
    optionGroups: [mockOptionGroups[0], mockOptionGroups[1], mockOptionGroups[2]],
    tags: ['熱門', '招牌'],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item002',
    name: '椒鹽雞排',
    description: '以椒鹽調味的香酥雞排，鹹香可口',
    categoryId: 'cat001',
    categoryName: '主餐',
    price: 95,
    imageUrl: 'https://example.com/images/pepper-chicken-main.jpg',
    thumbnailUrl: 'https://example.com/images/pepper-chicken-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 80,
    unit: '份',
    preparationTime: 5,
    isRecommended: false,
    isSpecial: false,
    isActive: true,
    optionGroups: [mockOptionGroups[1], mockOptionGroups[2]],
    tags: ['熱門'],
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item003',
    name: '韓式辣雞排',
    description: '以韓式辣醬醃製，香辣帶甜',
    categoryId: 'cat001',
    categoryName: '主餐',
    price: 100,
    discountPrice: 90,
    imageUrl: 'https://example.com/images/korean-chicken-main.jpg',
    thumbnailUrl: 'https://example.com/images/korean-chicken-thumb.jpg',
    stockStatus: 'low_stock',
    stockQuantity: 15,
    unit: '份',
    preparationTime: 6,
    isRecommended: true,
    isSpecial: true,
    isActive: true,
    optionGroups: [mockOptionGroups[0], mockOptionGroups[1], mockOptionGroups[2]],
    tags: ['熱門', '新品', '辣'],
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item004',
    name: '炸薯條',
    description: '香脆金黃的炸薯條，外酥內軟',
    categoryId: 'cat002',
    categoryName: '配餐',
    price: 50,
    imageUrl: 'https://example.com/images/fries-main.jpg',
    thumbnailUrl: 'https://example.com/images/fries-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 200,
    unit: '份',
    preparationTime: 3,
    isRecommended: false,
    isSpecial: false,
    isActive: true,
    tags: ['配餐', '人氣'],
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item005',
    name: '黃金薯餅',
    description: '外酥內軟的馬鈴薯餅，口感豐富',
    categoryId: 'cat002',
    categoryName: '配餐',
    price: 40,
    imageUrl: 'https://example.com/images/hashbrown-main.jpg',
    thumbnailUrl: 'https://example.com/images/hashbrown-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 150,
    unit: '片',
    preparationTime: 4,
    isRecommended: false,
    isSpecial: false,
    isActive: true,
    tags: ['配餐'],
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item006',
    name: '可樂',
    description: '冰涼的可口可樂',
    categoryId: 'cat003',
    categoryName: '飲料',
    price: 30,
    imageUrl: 'https://example.com/images/cola-main.jpg',
    thumbnailUrl: 'https://example.com/images/cola-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 300,
    unit: '杯',
    isRecommended: false,
    isSpecial: false,
    isActive: true,
    tags: ['飲料', '人氣'],
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item007',
    name: '芒果冰沙',
    description: '新鮮芒果打製的冰沙，清爽可口',
    categoryId: 'cat003',
    categoryName: '飲料',
    price: 70,
    imageUrl: 'https://example.com/images/mango-smoothie-main.jpg',
    thumbnailUrl: 'https://example.com/images/mango-smoothie-thumb.jpg',
    stockStatus: 'low_stock',
    stockQuantity: 20,
    unit: '杯',
    preparationTime: 3,
    isRecommended: true,
    isSpecial: true,
    isActive: true,
    tags: ['飲料', '人氣', '季節限定'],
    createdAt: '2025-01-07T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item008',
    name: '冰淇淋',
    description: '香濃滑順的香草冰淇淋',
    categoryId: 'cat004',
    categoryName: '甜點',
    price: 35,
    imageUrl: 'https://example.com/images/ice-cream-main.jpg',
    thumbnailUrl: 'https://example.com/images/ice-cream-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 100,
    unit: '份',
    isRecommended: false,
    isSpecial: false,
    isActive: true,
    tags: ['甜點'],
    createdAt: '2025-01-08T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item009',
    name: '超值雞排套餐',
    description: '包含雞排、薯條和飲料的超值套餐',
    categoryId: 'cat005',
    categoryName: '套餐',
    price: 150,
    discountPrice: 130,
    imageUrl: 'https://example.com/images/combo-main.jpg',
    thumbnailUrl: 'https://example.com/images/combo-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 50,
    unit: '套',
    preparationTime: 8,
    isRecommended: true,
    isSpecial: false,
    isActive: true,
    tags: ['套餐', '超值', '人氣'],
    createdAt: '2025-01-09T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item010',
    name: '芝士雞排堡',
    description: '炸雞排佐芝士，搭配特製醬料，夾在鬆軟麵包中',
    categoryId: 'cat001',
    categoryName: '主餐',
    price: 120,
    imageUrl: 'https://example.com/images/chicken-burger-main.jpg',
    thumbnailUrl: 'https://example.com/images/chicken-burger-thumb.jpg',
    stockStatus: 'out_of_stock',
    stockQuantity: 0,
    unit: '個',
    preparationTime: 7,
    isRecommended: false,
    isSpecial: false,
    isActive: false,
    optionGroups: [mockOptionGroups[0], mockOptionGroups[2]],
    tags: ['漢堡', '暫停供應'],
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item011',
    name: '花生雞排',
    description: '以花生醬調味的特製雞排，香甜可口',
    categoryId: 'cat006',
    categoryName: '季節限定',
    price: 110,
    imageUrl: 'https://example.com/images/peanut-chicken-main.jpg',
    thumbnailUrl: 'https://example.com/images/peanut-chicken-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 30,
    unit: '份',
    preparationTime: 6,
    isRecommended: true,
    isSpecial: true,
    isActive: true,
    optionGroups: [mockOptionGroups[1]],
    tags: ['季節限定', '新品'],
    createdAt: '2025-01-11T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  },
  {
    id: 'item012',
    name: '蜂蜜芥末雞排',
    description: '以蜂蜜芥末醬調味的雞排，香甜中帶點微辣',
    categoryId: 'cat006',
    categoryName: '季節限定',
    price: 115,
    discountPrice: 105,
    imageUrl: 'https://example.com/images/honey-mustard-chicken-main.jpg',
    thumbnailUrl: 'https://example.com/images/honey-mustard-chicken-thumb.jpg',
    stockStatus: 'in_stock',
    stockQuantity: 25,
    unit: '份',
    preparationTime: 6,
    isRecommended: true,
    isSpecial: true,
    isActive: true,
    optionGroups: [mockOptionGroups[1]],
    tags: ['季節限定', '新品', '推薦'],
    createdAt: '2025-01-12T00:00:00Z',
    updatedAt: '2025-01-15T08:30:00Z'
  }
]; 