openapi: 3.0.0
info:
  title: 考勤管理 API
  description: 提供考勤打卡和考勤記錄查詢等功能
  version: 1.0.0

tags:
  - name: attendance
    description: 考勤管理相關操作

paths:
  /attendance/punch:
    post:
      summary: 員工打卡
      description: 記錄員工的GPS打卡信息
      tags:
        - attendance
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PunchRequest'
      responses:
        '200':
          description: 打卡成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PunchResponse'
        '400':
          description: 請求數據格式錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 權限不足
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服務器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /attendance/logs:
    get:
      summary: 獲取考勤記錄列表
      description: 根據篩選條件獲取考勤記錄列表
      tags:
        - attendance
      security:
        - bearerAuth: []
      parameters:
        - name: employeeId
          in: query
          description: 按員工ID篩選
          required: false
          schema:
            type: string
        - name: storeId
          in: query
          description: 按分店ID篩選
          required: false
          schema:
            type: string
        - name: startDate
          in: query
          description: 開始日期（格式 YYYY-MM-DD）
          required: false
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: 結束日期（格式 YYYY-MM-DD）
          required: false
          schema:
            type: string
            format: date
        - name: type
          in: query
          description: 打卡類型
          required: false
          schema:
            type: string
            enum: [punch-in, punch-out]
        - name: isWithinFence
          in: query
          description: 是否在允許範圍內
          required: false
          schema:
            type: boolean
        - name: source
          in: query
          description: 打卡來源
          required: false
          schema:
            type: string
            enum: [mobile-app, web-admin-manual, kiosk]
        - name: limit
          in: query
          description: 每頁記錄數
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        - name: page
          in: query
          description: 頁碼
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: sortBy
          in: query
          description: 排序欄位
          required: false
          schema:
            type: string
            default: timestamp
            enum: [timestamp, employeeId, storeId, type, createdAt]
        - name: sortOrder
          in: query
          description: 排序方式
          required: false
          schema:
            type: string
            default: desc
            enum: [asc, desc]
      responses:
        '200':
          description: 成功獲取考勤記錄列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceLogsResponse'
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 權限不足
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服務器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    PunchRequest:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          description: 緯度
          example: 25.0330
        longitude:
          type: number
          description: 經度
          example: 121.5654
        deviceInfo:
          type: object
          description: 設備信息
          properties:
            deviceId:
              type: string
              description: 設備ID
            platform:
              type: string
              description: 平台
              enum: [iOS, Android, Web]
            model:
              type: string
              description: 設備型號
            osVersion:
              type: string
              description: 操作系統版本
        notes:
          type: string
          description: 備註

    PunchResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
        message:
          type: string
        data:
          type: object
          properties:
            logId:
              type: string
              description: 打卡記錄ID
            timestamp:
              type: string
              format: date-time
              description: 打卡時間
            type:
              type: string
              enum: [punch-in, punch-out]
              description: 打卡類型
            isWithinFence:
              type: boolean
              description: 是否在允許範圍內
            distance:
              type: number
              description: 與分店中心點的距離(公尺)
            storeName:
              type: string
              description: 分店名稱
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string

    AttendanceLog:
      type: object
      properties:
        logId:
          type: string
          description: 打卡記錄唯一識別碼
        employeeId:
          type: string
          description: 員工ID
        employeeName:
          type: string
          description: 員工姓名
        storeId:
          type: string
          description: 分店ID
        storeName:
          type: string
          description: 分店名稱
        tenantId:
          type: string
          description: 租戶ID
        timestamp:
          type: string
          format: date-time
          description: 打卡時間
        type:
          type: string
          enum: [punch-in, punch-out]
          description: 打卡類型 (上班/下班)
        latitude:
          type: number
          description: 緯度
        longitude:
          type: number
          description: 經度
        isWithinFence:
          type: boolean
          description: 是否在允許範圍內
        distance:
          type: number
          description: 與分店中心點的距離(公尺)
        source:
          type: string
          enum: [mobile-app, web-admin-manual, kiosk]
          description: 來源
        notes:
          type: string
          description: 備註
        createdAt:
          type: string
          format: date-time
          description: 記錄創建時間
        createdBy:
          type: string
          description: 記錄創建者 (若為手動調整)
        updatedAt:
          type: string
          format: date-time
          description: 記錄更新時間
        updatedBy:
          type: string
          description: 記錄更新者

    AttendanceLogsResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
        data:
          type: array
          items:
            $ref: '#/components/schemas/AttendanceLog'
        pagination:
          type: object
          properties:
            currentPage:
              type: integer
              description: 當前頁碼
            totalPages:
              type: integer
              description: 總頁數
            totalItems:
              type: integer
              description: 總記錄數
            limit:
              type: integer
              description: 每頁記錄數
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          default: error
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string 