/**
 * 排班系統的資料類型定義
 */

import { Timestamp } from 'firebase-admin/firestore';

/**
 * 排班資料結構
 */
export interface Schedule {
  scheduleId: string;       // 主鍵，排班ID
  tenantId: string;         // 租戶ID（隔離欄位）
  storeId: string;          // 分店ID
  employeeId: string;       // 員工ID
  shiftDate: string;        // 班次日期 (YYYY-MM-DD)
  startTime: string;        // 開始時間 (HH:MM)
  endTime: string;          // 結束時間 (HH:MM)
  role: string;             // 班次角色: cashier, kitchen, server, manager
  status: ScheduleStatus;   // 狀態: draft, published, confirmed, completed, cancelled
  publishedAt?: Timestamp;  // 發布時間
  confirmedAt?: Timestamp;  // 員工確認時間
  createdBy: string;        // 創建者ID
  createdAt: Timestamp;     // 創建時間
  updatedAt: Timestamp;     // 更新時間
  notes?: string;           // 備註
  isAutoGenerated: boolean; // 是否自動生成
}

/**
 * 排班狀態枚舉
 */
export type ScheduleStatus = 'draft' | 'published' | 'confirmed' | 'completed' | 'cancelled';

/**
 * 班次類型
 */
export interface ShiftType {
  shiftTypeId: string;      // 主鍵，班次類型ID
  tenantId: string;         // 租戶ID（隔離欄位）
  storeId: string;          // 分店ID
  name: string;             // 班次名稱
  startTime: string;        // 默認開始時間 (HH:MM)
  endTime: string;          // 默認結束時間 (HH:MM)
  color: string;            // 顏色識別碼
  minimumStaff: number;     // 最低人力需求
  roles: string[];          // 所需角色列表
  createdAt: Timestamp;     // 創建時間
  updatedAt: Timestamp;     // 更新時間
  isActive: boolean;        // 是否啟用
}

/**
 * 自動排班設定
 */
export interface AutoScheduleSetting {
  settingId: string;        // 主鍵，設定ID
  tenantId: string;         // 租戶ID（隔離欄位）
  storeId: string;          // 分店ID
  maxHoursPerWeek: Record<string, number>; // 各職位每週最大工時
  minHoursPerWeek: Record<string, number>; // 各職位每週最小工時
  minStaffPerShift: Record<string, number>; // 各班次最低人力需求
  preferredEmployees: Record<string, string[]>; // 各班次優先考慮的員工
  avoidContinuousShifts: boolean; // 避免連續班次
  respectPreferences: boolean; // 尊重員工偏好
  createdAt: Timestamp;     // 創建時間
  updatedAt: Timestamp;     // 更新時間
  isActive: boolean;        // 是否啟用
}

/**
 * 排班週期
 */
export interface SchedulePeriod {
  periodId: string;         // 主鍵，週期ID
  tenantId: string;         // 租戶ID（隔離欄位）
  storeId: string;          // 分店ID
  startDate: string;        // 開始日期 (YYYY-MM-DD)
  endDate: string;          // 結束日期 (YYYY-MM-DD)
  status: PeriodStatus;     // 狀態: draft, published, archived
  publishedAt?: Timestamp;  // 發布時間
  createdBy: string;        // 創建者ID
  createdAt: Timestamp;     // 創建時間
  updatedAt: Timestamp;     // 更新時間
  notes?: string;           // 備註
}

/**
 * 週期狀態枚舉
 */
export type PeriodStatus = 'draft' | 'published' | 'archived';

/**
 * 調班請求
 */
export interface ShiftSwapRequest {
  requestId: string;        // 主鍵，請求ID
  tenantId: string;         // 租戶ID（隔離欄位）
  storeId: string;          // 分店ID
  requesterId: string;      // 請求者ID
  originalScheduleId: string; // 原排班ID
  targetEmployeeId?: string; // 目標員工ID (如果指定)
  targetDate?: string;      // 目標日期 (YYYY-MM-DD) (如果是調日期)
  reason: string;           // 申請原因
  status: SwapRequestStatus; // 狀態: pending, approved, rejected, cancelled
  approverNotes?: string;   // 審批者備註
  approverId?: string;      // 審批者ID
  approvedAt?: Timestamp;   // 審批時間
  responderId?: string;     // 回應者ID (同意換班的員工)
  responseDate?: Timestamp; // 回應時間
  createdAt: Timestamp;     // 創建時間
  updatedAt: Timestamp;     // 更新時間
}

/**
 * 調班請求狀態枚舉
 */
export type SwapRequestStatus = 'pending' | 'approved' | 'rejected' | 'cancelled';

/**
 * 禁止排班日期 
 */
export interface RestrictedDate {
  restrictedDateId: string; // 主鍵，禁排日ID
  tenantId: string;         // 租戶ID（隔離欄位）
  storeId: string;          // 分店ID
  date: string;             // 日期 (YYYY-MM-DD)
  reason: string;           // 原因
  createdBy: string;        // 創建者ID
  createdAt: Timestamp;     // 創建時間
  updatedAt: Timestamp;     // 更新時間
  isActive: boolean;        // 是否啟用
} 